version: "3"
services:
  app:
    build: ./infra/php
    volumes:
      - ./backend:/work
  
  web:
    build:
      context: .
      dockerfile: ./infra/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./backend:/work
  
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: sample
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: